var PropsSprites = {
    'TAPIS': 0,
    'TABLE': 1,
    'TABLEAU': 2,
    'CLEF': 4,
    'PUIT': 5,
    'MUR': 6,
    'TANK': 7,
    'DRAPCOM': 8,
    'LIVRE': 9,
    'OBAMA': 10,
    'BENLADEN': 11,
    'YANOUKOVIC': 12,
    'FEMINISTE': 13,
    'OURS': 14,
    'VODKA': 15,
    'CAVIAR': 16,
    'CIGARETTE': 17,
    'PORTECRIMEA': 18,
    'PEAUOURS': 19,
}
