var PropsSprites = {
    'TAPIS': "",
    'TABLE': "Table.png",
    'TABLEAU': "",
    'CLEF': "",
    'PUIT': "",
    'MUR': "",
    'TANK': "",
    'DRAPCOM': "",
    'LIVRE': "LivreKarlM.png",
    'OBAMA': "",
    'BENLADEN': "",
    'YANOUKOVIC': "",
    'FEMINISTE': "",
    'OURS': "bear.png",
    'VODKA': "",
    'CAVIAR': "Caviar.png",
    'CIGARETTE': "PaquetC.png",
    'PORTECRIMEA': "",
    'PEAUOURS': ""
};
